### ISSUE TITLE
Request for BinPRE Benchmarks Access

### ISSUE THREAD

**Issue by YihuaXuCn** [BinPRE/BinPRE#5]
I recently read your paper on BinPRE and found your work highly inspiring. I am interested in conducting further research based on your findings. I would like to know if you can share the evaluation data used in your paper, including all server binary files, pcap files, and their ground truth files. I also sent emails to y'all. I am looking forward to hearing from y'all.

**Comment by jyjsunny** [comment]
Thank you for your question, and I apologize for the delayed response. Since the projects and datasets in our evaluation are open-source, you are welcome to download and install them on your own. 
More details of the benchmark (e.g., protocol implementation projects, message datasets) could be found in the full version paper of BinPRE https://arxiv.org/pdf/2409.01994.

**Comment by macromogic** [comment]
Hello,

Could you also show how you obtained the packets for Ethernet/IP? I noticed that you used OpENer as the server side but the data source is unclear in the arXiv version. Thank you.
